"""
Terra-OS ↔ n8n Integration Client.

Manages n8n workflows programmatically:
- List/create/activate workflows
- Register webhooks
- Trigger workflow executions
- Provision credentials

Simply-clever: Terra-OS manages n8n without user touching n8n UI.
"""
import os
import json
import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

N8N_BASE_URL = os.getenv("N8N_BASE_URL", "http://localhost:5678")
N8N_API_KEY = os.getenv("N8N_API_KEY", "")


class N8nClient:
    """Synchronous n8n API client for Terra-OS backend."""

    def __init__(self, base_url: str = None, api_key: str = None):
        self.base_url = (base_url or N8N_BASE_URL).rstrip("/")
        self.api_key = api_key or N8N_API_KEY
        self._headers = {
            "X-N8N-API-KEY": self.api_key,
            "Content-Type": "application/json",
        }

    def _get(self, path: str) -> dict:
        with httpx.Client(timeout=10.0) as c:
            r = c.get(f"{self.base_url}{path}", headers=self._headers)
            r.raise_for_status()
            return r.json()

    def _post(self, path: str, data: dict) -> dict:
        with httpx.Client(timeout=10.0) as c:
            r = c.post(f"{self.base_url}{path}", headers=self._headers, json=data)
            r.raise_for_status()
            return r.json()

    # ─── Workflows ────────────────────────────────���───────────────────────────

    def list_workflows(self) -> list[dict]:
        """List all workflows."""
        resp = self._get("/api/v1/workflows")
        return resp.get("data", [])

    def get_workflow(self, wf_id: str) -> dict:
        """Get workflow details."""
        return self._get(f"/api/v1/workflows/{wf_id}")

    def create_workflow(self, workflow: dict) -> dict:
        """Create a new workflow. Strip 'meta' if present."""
        wf = {k: v for k, v in workflow.items() if k != "meta"}
        return self._post("/api/v1/workflows", wf)

    def activate_workflow(self, wf_id: str) -> dict:
        """Activate a workflow (starts webhook listeners)."""
        return self._post(f"/api/v1/workflows/{wf_id}/activate", {})

    def deactivate_workflow(self, wf_id: str) -> dict:
        """Deactivate a workflow."""
        return self._post(f"/api/v1/workflows/{wf_id}/deactivate", {})

    # ─── Health ───────────────────────────────────────────────────────────────

    def health(self) -> dict:
        """Check n8n health."""
        try:
            with httpx.Client(timeout=5.0) as c:
                r = c.get(f"{self.base_url}/healthz")
                return r.json()
        except Exception as e:
            return {"status": "error", "detail": str(e)}

    # ─── Webhook URLs ─────────────────────────────────────────────────────────

    def get_webhook_urls(self) -> list[dict]:
        """Get all registered webhook URLs from active workflows."""
        workflows = self.list_workflows()
        webhooks = []
        for wf in workflows:
            if not wf.get("active"):
                continue
            for node in wf.get("nodes", []):
                if node.get("type") == "n8n-nodes-base.webhook":
                    path = node.get("parameters", {}).get("path", "")
                    webhooks.append({
                        "workflow_id": wf["id"],
                        "workflow_name": wf["name"],
                        "webhook_path": path,
                        "url": f"{self.base_url}/webhook/{path}",
                        "test_url": f"{self.base_url}/webhook-test/{path}",
                    })
        return webhooks

    # ─── Terra-OS Specific ────────────────────────────────────────────────────

    def provision_terra_webhook(self, event_name: str, webhook_path: str = None) -> dict:
        """
        Create a minimal webhook-receiver workflow for a Terra-OS event.
        Returns workflow ID and webhook URL.
        """
        path = webhook_path or f"terra-{event_name.replace('.', '-')}"
        
        workflow = {
            "name": f"Terra-OS: {event_name}",
            "nodes": [
                {
                    "parameters": {
                        "httpMethod": "POST",
                        "path": path,
                        "responseMode": "onReceived",
                    },
                    "id": "webhook-auto",
                    "name": "Terra Webhook",
                    "type": "n8n-nodes-base.webhook",
                    "typeVersion": 2,
                    "position": [240, 300],
                },
                {
                    "parameters": {
                        "jsCode": f"// Auto-generated by Terra-OS for event: {event_name}\n"
                                  "const body = $input.first().json.body;\n"
                                  "return [{ json: body }];",
                    },
                    "id": "code-auto",
                    "name": "Process Event",
                    "type": "n8n-nodes-base.code",
                    "typeVersion": 2,
                    "position": [460, 300],
                },
            ],
            "connections": {
                "Terra Webhook": {
                    "main": [[{"node": "Process Event", "type": "main", "index": 0}]]
                }
            },
            "settings": {"executionOrder": "v1"},
        }

        result = self.create_workflow(workflow)
        return {
            "workflow_id": result.get("id"),
            "webhook_url": f"{self.base_url}/webhook/{path}",
            "test_url": f"{self.base_url}/webhook-test/{path}",
        }


# Singleton
_client: N8nClient | None = None


def get_n8n_client() -> N8nClient:
    global _client
    if _client is None:
        _client = N8nClient()
    return _client
